version: '3.4'
services:
  core:
    container_name: about-you-core
    build:
      context: .
      dockerfile: docker/core/Dockerfile
    env_file:
      - ./.env.docker
    ports:
      - "8008:80"
    volumes:
      - .:/var/www
