version: '3.4'
services:
  core:
    container_name: about-you-core
    build:
      context: .
      dockerfile: docker/core/Dockerfile
    depends_on:
      - db
    env_file:
      - ./.env.docker
    ports:
      - "8008:80"
    volumes:
      - .:/var/www

  db:
    image: mysql:8
    container_name: about-you-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 8306:3306
    environment:
      TZ: 'Europe/Helsinki'
      MYSQL_ROOT_PASSWORD: localhostrootpwd
      MYSQL_DATABASE: aboutyoutest
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./docker`/mysql/conf.d:/etc/mysql/conf.d

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: about-you-swagger-ui
    ports:
      - "8009:8080"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
#      API_URL: "http://localhost:8008"
