FROM php:7.3-fpm

WORKDIR /var/www

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
    libcurl4-gnutls-dev \
    libgeoip-dev \
    libpq-dev \
    libxml2-dev \
    libzip-dev \
    locales \
    unzip \
    inetutils-syslogd \
    ca-certificates \
    libpng-dev \
    nginx-light

RUN apt-get install -y libmagickwand-dev --no-install-recommends
RUN rm -rf /var/lib/apt/lists/*

# Install needed PHP extensions
RUN docker-php-ext-install bcmath curl gettext pdo_mysql pdo_pgsql posix soap sockets zip gd
RUN pecl install redis imagick && docker-php-ext-enable redis imagick

RUN dpkg -P libzip-dev libgeoip-dev

EXPOSE 8000